{application,earmark,
             [{optional_applications,[]},
              {applications,[kernel,stdlib,elixir,eex,earmark_parser]},
              {description,"Earmark is a pure-Elixir Markdown converter.\n\nIt is intended to be used as a library (just call Earmark.as_html),\nbut can also be used as a command-line tool (run mix escript.build\nfirst).\n\nOutput generation is pluggable.\n"},
              {modules,['Elixir.Earmark','Elixir.Earmark.AstTools',
                        'Elixir.Earmark.Cli',
                        'Elixir.Earmark.Cli.Implementation',
                        'Elixir.Earmark.EarmarkParserProxy',
                        'Elixir.Earmark.Error','Elixir.Earmark.Helpers',
                        'Elixir.Earmark.Internal','Elixir.Earmark.Message',
                        'Elixir.Earmark.Options','Elixir.Earmark.Restructure',
                        'Elixir.Earmark.SysInterface',
                        'Elixir.Earmark.TagSpecificProcessors',
                        'Elixir.Earmark.Transform',
                        'Elixir.Earmark.Transform.Pop']},
              {registered,[]},
              {vsn,"1.4.39"}]}.
